# Generated by Django 3.1.1 on 2020-10-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebPImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('static_path', models.CharField(max_length=512)),
                ('quality', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('static_path', 'quality')},
            },
        ),
    ]
